[package]
name = "genemichaels"
version = "0.1.12"
edition = "2021"
license = "ISC"
description = "Makes your code formatty"
repository = "https://github.com/andrewbaxter/genemichaels"
readme = "readme.md"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.29", features = ["derive"] }
markdown = { git = "https://github.com/wooorm/markdown-rs", rev = "af202d3f0ea24e0a957b02a6f9fb23c6c3b4afe7" }
proc-macro2 = { version = "1.0.49", features = ["span-locations"] }
quote = "1.0.23"
structre = "0.0.1"
syn = { version = "1.0.107", features = ["full"] }

# UNUSED?
# icu_segmenter = { version = "0.7.0", features = ["lstm"] }
# icu_testdata = "1.0.0"
